# Header
menu:
  归档: archives
  分类: categories
  标签: tags
  链接: links
  关于: about
rss: atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: false
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
analytics: true
favicon: favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: